"""
Django settings for reader project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import socket


#if not os.environ['API_TOCKEN']:
#    raise Exception("API_TOKEN not set")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
base_dir = os.getenv('BASE_DIR')

if base_dir is None:
    raise ValueError("BASE_DIR environment variable is not set")

DJANGO_BASE_DIR = Path(base_dir)  



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!

if socket.gethostname().startswith('vps'):

    DEBUG = False
    ALLOWED_HOSTS = [os.getenv("ALLOWED_HOSTS")]
    CSRF_TRUSTED_ORIGINS = ['https://ai-demo.fr', 'https://www.ai-demo.fr']
    SECRET_KEY = os.getenv("SECRET_KEY")
    STATIC_ROOT = "/var/www/ai-demo.fr/static"
    STATIC_URL = "/static/"
    MEDIA_ROOT = "/var/www/ai-demo.com/media"
    MEDIA_URL = '/media/'
else:
    DEBUG = True
    ALLOWED_HOSTS = []
    SECRET_KEY = 'django-insecure--vdawxap(t_*2(kfc153r+#c3*rsws$a$da#ft9i76h#)6lb(r'
    
    STATIC_URL = 'static/'
    # STATIC_ROOT is optional in development
    # Add only if you need to test collectstatic
    # STATIC_ROOT = BASE_DIR / 'staticfiles'
   

# This will change
ENGINE = 'django.db.backends.sqlite3'
NAME = 'db.sqlite3'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'book_assistant.phase1.apps.Phase1Config'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'reader.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [DJANGO_BASE_DIR / 'phase1/templates'],
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'reader.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DJANGO_BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

#Let Django find satic files in the app directories
# STATICFILES_DIRS = [
#     DJANGO_BASE_DIR / "static",
#     DJANGO_BASE_DIR / "phase1/static",
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
